title:             Study Blog
email:             nay0824@korea.ac.kr
description:       A Blog for study cyber security
author:            
baseurl:           
url:               "http://iye0n.github.io"

# Social Profiles
twitter_username:  none
github_username:   iye0n
facebook_username: none

# Build settings
# category_dir: category/
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
